#!/bin/bash
REPO_NAME=nacos
DEFAULT_BRANCH=develop
cd ${REPO_NAME}
if ! git remote | grep -q "^${REPO_NAME}\$"; then
	git remote add ${REPO_NAME} https://github.com/alibaba/nacos.git
fi
git pull ${REPO_NAME} ${DEFAULT_BRANCH}
git push origin ${DEFAULT_BRANCH}
git fetch ${REPO_NAME} --tags ${DEFAULT_BRANCH}
git push origin ${DEFAULT_BRANCH} --tags
